#!/bin/sh
#
# Regenerates ../ps3gl_shader_data.h. NOT part of the normal build: the
# header is in the tree, so building the game needs neither of these tools.
#
# Needs:
#   cgc      NVIDIA Cg Toolkit 3.1, Linux build. On Ubuntu/WSL:
#              sudo apt install nvidia-cg-toolkit
#   cgcomp   PSL1GHT's, only its assembler mode (-a): $PS3DEV/bin/cgcomp
#   python3
#
# cgc turns Cg into NV40 assembly (profiles vp40 / fp40), cgcomp -a turns
# the assembly into the .vpo/.fpo binaries PSL1GHT loads (IoQuake3-PS3's
# and Quake2PS3's method). The fragment programs are generated by
# gen_fp.py, one per texture environment combination.
#
#   cd tyrquake-ps3/common/gl/shaders && sh build_shaders.sh

set -e

CGC=${CGC:-cgc}
CGCOMP=${CGCOMP:-$PS3DEV/bin/cgcomp}

command -v "$CGC" >/dev/null 2>&1 || { echo "cgc not found (sudo apt install nvidia-cg-toolkit)"; exit 1; }
[ -x "$CGCOMP" ] || { echo "cgcomp not found at $CGCOMP"; exit 1; }

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

"$CGC" -quiet -profile vp40 -o "$TMP/tq_vp.asm" tq_vp.vcg
"$CGCOMP" -a -v "$TMP/tq_vp.asm" "$TMP/tq_vp.vpo" >/dev/null

"$CGC" -quiet -profile fp40 -o "$TMP/tq_fp_present.asm" tq_fp_present.fcg
"$CGCOMP" -a -f "$TMP/tq_fp_present.asm" "$TMP/tq_fp_present.fpo" >/dev/null

FPS=$(python3 gen_fp.py "$TMP")
for fp in $FPS; do
	"$CGC" -quiet -profile fp40 -o "$TMP/$fp.asm" "$TMP/$fp.fcg"
	"$CGCOMP" -a -f "$TMP/$fp.asm" "$TMP/$fp.fpo" >/dev/null
done

python3 - "$TMP" $FPS <<'PYEOF'
import sys
tmp = sys.argv[1]
fps = sys.argv[2:]
out = ["/* ps3gl_shader_data.h -- GENERATED by shaders/build_shaders.sh, don't edit.",
       " * Compiled RSX programs (cgc vp40/fp40 + PSL1GHT cgcomp -a) of the Cg",
       " * sources in shaders/ (the fragment programs come from gen_fp.py). */",
       "",
       "#ifndef PS3GL_SHADER_DATA_H",
       "#define PS3GL_SHADER_DATA_H",
       ""]
def emit(name, path):
    data = open(path, "rb").read()
    out.append("static const unsigned char %s[] __attribute__((aligned(16))) = {" % name)
    for i in range(0, len(data), 12):
        out.append("\t" + ", ".join("0x%02x" % b for b in data[i:i+12]) + ",")
    out.append("};")
    out.append("")
emit("tq_vp_vpo", tmp + "/tq_vp.vpo")
emit("tq_fp_present_fpo", tmp + "/tq_fp_present.fpo")
for fp in fps:
    emit(fp + "_fpo", tmp + "/" + fp + ".fpo")
out.append("/* indexed by unit0 + 4 * (unit1 + 5 * unit2), see gen_fp.py */")
out.append("#define PS3GL_NUM_FP %d" % len(fps))
out.append("static const unsigned char *const ps3gl_fp_data[PS3GL_NUM_FP] = {")
for fp in fps:
    out.append("\t%s_fpo," % fp)
out.append("};")
out.append("")
out.append("#endif")
open("../ps3gl_shader_data.h", "w").write("\n".join(out) + "\n")
print("wrote ../ps3gl_shader_data.h (%d fragment programs)" % len(fps))
PYEOF
