#!/usr/bin/env python3
#
# Writes the Cg sources of ps3gl's fragment programs into the directory
# given as argument, one per combination of the texture units' modes
# (GL's fixed function texture environment, see ps3gl_draw.c ChooseFP):
#
#   unit 0: 0 off (vertex color), 1 GL_REPLACE, 2 GL_MODULATE,
#           3 GL_COMBINE modulate x2 (texture * color * 2)
#   unit 1: 0 off, 1 GL_MODULATE, 2 x2 (GL_COMBINE, GL_RGB_SCALE 2),
#           3 x4, 4 GL_DECAL
#   unit 2: 0 off, 1 GL_DECAL (sampled with texture coordinate 0: TyrQuake
#           only uses unit 2 for fullbright masks over the base texture)
#
# Names: tq_fp_<u0>_<u1>_<u2>. GL clamps every stage's result, so do we.

import sys

U0 = 4
U1 = 5
U2 = 2

def source(u0, u1, u2):
    body = []
    if u0 == 0:
        body.append("c = color;")
    elif u0 == 1:
        body.append("c = tex2D(tex0, tc0);")
    elif u0 == 2:
        body.append("c = tex2D(tex0, tc0) * color;")
    else:
        body.append("t = tex2D(tex0, tc0) * color;")
        body.append("c = float4(saturate(t.rgb * 2.0), t.a);")
    if u1 == 1:
        body.append("c = c * tex2D(tex1, tc1);")
    elif u1 in (2, 3):
        body.append("t = c * tex2D(tex1, tc1);")
        body.append("c = float4(saturate(t.rgb * %s), t.a);" % ("2.0" if u1 == 2 else "4.0"))
    elif u1 == 4:
        body.append("t = tex2D(tex1, tc1);")
        body.append("c.rgb = lerp(c.rgb, t.rgb, t.a);")
    if u2 == 1:
        body.append("t = tex2D(tex2, tc0);")
        body.append("c.rgb = lerp(c.rgb, t.rgb, t.a);")
    return (
        "/* generated by gen_fp.py: unit0 %d, unit1 %d, unit2 %d */\n"
        "void main(float4 color : COLOR0, float2 tc0 : TEXCOORD0, float2 tc1 : TEXCOORD1,\n"
        "          uniform sampler2D tex0 : TEXUNIT0, uniform sampler2D tex1 : TEXUNIT1,\n"
        "          uniform sampler2D tex2 : TEXUNIT2, out float4 oColor : COLOR)\n"
        "{\n"
        "    float4 c, t;\n"
        "    %s\n"
        "    oColor = c;\n"
        "}\n" % (u0, u1, u2, "\n    ".join(body)))

def names():
    for u2 in range(U2):
        for u1 in range(U1):
            for u0 in range(U0):
                yield (u0, u1, u2)

if __name__ == "__main__":
    out = sys.argv[1]
    for u0, u1, u2 in names():
        with open("%s/tq_fp_%d_%d_%d.fcg" % (out, u0, u1, u2), "w") as f:
            f.write(source(u0, u1, u2))
    print(" ".join("tq_fp_%d_%d_%d" % n for n in names()))
